AWSTemplateFormatVersion: 2010-09-09
Description: Template for our assignment 3 implementation
Resources:

#Comment out OpenSearch resources until we are ready to use them
#  PhotosDomain:
#    Type: AWS::OpenSearchService::Domain
#    Properties:
#      DomainName: photos

  B2:
    Type: AWS::S3::Bucket
    #B2Permission needs to be created first so that B2 has correct permissions for
    #lambda coonfigurations.
    DependsOn: B2Permission
    Properties:
      BucketName: photosBucket
      NotificationConfiguration:
        #Allows S3 to use put method on LF1
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg
            Function: !GetAtt LF1.Arn

  B2Permission:
    #Gives B2 permision to invoke LF1
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LF1
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::photosBucket

  LF1:
    Type: AWS::Lambda::Function
    DependsOn: LF1IAMRole
    Properties:
      #IAM Role that LF1 must assume.
      Role: !GetAtt LF1IAMRole.Arn
      Runtime: python3.14
      FunctionName: index-photos
      #Source code for lambda function
      Code:
        ZipFile: |
          def main(event, context):
            Return "Hello World!"
      Handler: index.main

  LF1IAMRole:
    Type: AWS::IAM::Role
    Properties:
      #Allows a lambda instance to assume this role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      #Allows a lambda to write logs to cloudwatch
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      #Provides the necessary permissions to lambda
      Policies:
        - PolicyName: LF1Permissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                #The /* gives the lambda object leve interactions. Without it,
                #it can only perform bucket level actions like deleting the bucket.
                #Hardcoding the arn for B2 is considered bad practice. It is done
                #here to break the dependency loop B2->LF1->LF1IAMRole->B2
                Resource: "arn:aws:s3:::photosBucket/*"
              - Effect: Allow
                Action: rekognition:DetectLabels
                #Wild card is used instead of ARN, because Rekognition
                #is an API based service, so there is no specific ARN
                #that it needs access to.
                Resource: "*"
#              - Effect: Allow
#                Action:
#                  - es:ESHttpPost
#                  - es:ESHttpPut
#                  - es:ESHttpDelete
#                Resource: !Sub
#                  - "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${DomainName}/photos/*"
#                  #Pulls physical domain name assigned when open search instance is created
#                  - DomainName: !GetAtt PhotosDomain.DomainName