version: 0.2

phases:
  build:
    commands:
      - zip lf1.zip lf1.py
      - zip lf2.zip lf2.py

artifacts:
  secondary-artifacts:
    lf1Artifact:
      files:
        - lf1.zip
    lf2Artifact:
      files:
      - lf2.zip