version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.14
    command:
      - python -m pip install --upgrade pip
      - pip install --target package opensearch-py requests-aws4auth
  build:
    commands:
      - cp lf1.py package/
      - cp lf2.py package/
      - cd package
      - zip -r ../lf1.zip lf1.py opensearchpy requests_aws4auth
      - zip -r ../lf2.zip lf2.py opensearchpy requests_aws4auth
      - cd ..

artifacts:
  #Dummy for primary artifact
  files:
    -  dummy.txt
  secondary-artifacts:
    BuildArtifactLF1:
      files:
        - lf1.zip
    BuildArtifactLF2:
      files:
        - lf2.zip