version: 0.2

phases:
  build:
    commands:
      - echo "Zipping lf1.py"
      - zip lf1.zip lf1.py

      - echo "Zipping lf2.py"
      - zip lf2.zip lf2.py

artifacts:
  files:
    - lf1.zip
    - lf2.zip