version: 0.2

phases:
  build:
    commands:
      - zip lf1.zip lf1.py

artifacts:
  #Dummy for primary artifact
  files:
    -  dummy.txt
  secondary-artifacts:
    BuildArtifactLF1:
      files:
        - lf1.zip
    BuildArtifactLF2:
      files:
        - lf2.zip